/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/SearchRadiusContext`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/afterGenre`; params?: Router.UnknownInputParams; } | { pathname: `/auth/interests-selection`; params?: Router.UnknownInputParams; } | { pathname: `/auth/language-selection`; params?: Router.UnknownInputParams; } | { pathname: `/auth/radius-selection`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/splash-screen`; params?: Router.UnknownInputParams; } | { pathname: `/dev/users`; params?: Router.UnknownInputParams; } | { pathname: `/home/details`; params?: Router.UnknownInputParams; } | { pathname: `/home/genre`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/language`; params?: Router.UnknownInputParams; } | { pathname: `/home/player`; params?: Router.UnknownInputParams; } | { pathname: `/home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/home/search`; params?: Router.UnknownInputParams; } | { pathname: `/itinerary/custom-route`; params?: Router.UnknownInputParams; } | { pathname: `/itinerary/edit`; params?: Router.UnknownInputParams; } | { pathname: `/itinerary/map`; params?: Router.UnknownInputParams; } | { pathname: `/itinerary/recommended-route`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/SearchRadiusContext`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/afterGenre`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/interests-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/language-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/radius-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/splash-screen`; params?: Router.UnknownOutputParams; } | { pathname: `/dev/users`; params?: Router.UnknownOutputParams; } | { pathname: `/home/details`; params?: Router.UnknownOutputParams; } | { pathname: `/home/genre`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/home/language`; params?: Router.UnknownOutputParams; } | { pathname: `/home/player`; params?: Router.UnknownOutputParams; } | { pathname: `/home/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/home/search`; params?: Router.UnknownOutputParams; } | { pathname: `/itinerary/custom-route`; params?: Router.UnknownOutputParams; } | { pathname: `/itinerary/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/itinerary/map`; params?: Router.UnknownOutputParams; } | { pathname: `/itinerary/recommended-route`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/SearchRadiusContext${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/afterGenre${`?${string}` | `#${string}` | ''}` | `/auth/interests-selection${`?${string}` | `#${string}` | ''}` | `/auth/language-selection${`?${string}` | `#${string}` | ''}` | `/auth/radius-selection${`?${string}` | `#${string}` | ''}` | `/auth/signin${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/auth/splash-screen${`?${string}` | `#${string}` | ''}` | `/dev/users${`?${string}` | `#${string}` | ''}` | `/home/details${`?${string}` | `#${string}` | ''}` | `/home/genre${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/home/language${`?${string}` | `#${string}` | ''}` | `/home/player${`?${string}` | `#${string}` | ''}` | `/home/profile${`?${string}` | `#${string}` | ''}` | `/home/search${`?${string}` | `#${string}` | ''}` | `/itinerary/custom-route${`?${string}` | `#${string}` | ''}` | `/itinerary/edit${`?${string}` | `#${string}` | ''}` | `/itinerary/map${`?${string}` | `#${string}` | ''}` | `/itinerary/recommended-route${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/SearchRadiusContext`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/afterGenre`; params?: Router.UnknownInputParams; } | { pathname: `/auth/interests-selection`; params?: Router.UnknownInputParams; } | { pathname: `/auth/language-selection`; params?: Router.UnknownInputParams; } | { pathname: `/auth/radius-selection`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/splash-screen`; params?: Router.UnknownInputParams; } | { pathname: `/dev/users`; params?: Router.UnknownInputParams; } | { pathname: `/home/details`; params?: Router.UnknownInputParams; } | { pathname: `/home/genre`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/language`; params?: Router.UnknownInputParams; } | { pathname: `/home/player`; params?: Router.UnknownInputParams; } | { pathname: `/home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/home/search`; params?: Router.UnknownInputParams; } | { pathname: `/itinerary/custom-route`; params?: Router.UnknownInputParams; } | { pathname: `/itinerary/edit`; params?: Router.UnknownInputParams; } | { pathname: `/itinerary/map`; params?: Router.UnknownInputParams; } | { pathname: `/itinerary/recommended-route`; params?: Router.UnknownInputParams; };
    }
  }
}
